SELECT BOARD_ID, WRITER_ID, TITLE, PRICE,
    CASE
        WHEN (STATUS like 'SALE') THEN '판매중'
        WHEN (STATUS like 'DONE') THEN '거래완료'
        WHEN (STATUS like 'RESERVED') THEN '예약중'
    END AS STATUS    
FROM USED_GOODS_BOARD
WHERE CREATED_DATE like '2022-10-05'
ORDER BY BOARD_ID DESC