SELECT A.CATEGORY , A.PRICE , B.PRODUCT_NAME 
FROM (
        SELECT 
                 CATEGORY, MAX(PRICE) PRICE
        FROM FOOD_PRODUCT
        WHERE CATEGORY IN ('과자','국','김치','식용유')
        GROUP BY CATEGORY
) A
INNER JOIN FOOD_PRODUCT B ON A.CATEGORY =B.CATEGORY AND A.PRICE = B.PRICE
ORDER BY A.PRICE DESC