SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
COUNT(DISTINCT S.USER_ID) AS PUCHASED_USERS, 
ROUND( COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(*)
                                    FROM USER_INFO
                                    WHERE YEAR(JOINED) = '2021'),1) AS PUCHASED_RATIO
FROM USER_INFO AS UI, ONLINE_SALE AS S
WHERE YEAR(UI.JOINED) = '2021' AND UI.USER_ID = S.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE) 
ORDER BY YEAR, MONTH;