SELECT p.PRODUCT_CODE, SUM(o.SALES_AMOUNT * p.PRICE) as SALES
FROM OFFLINE_SALE o
INNER JOIN PRODUCT p ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY o.PRODUCT_ID 
ORDER BY SUM(o.SALES_AMOUNT * p.PRICE) DESC, p.PRODUCT_CODE