SELECT RH.HISTORY_ID, RH.CAR_ID, 
    DATE_FORMAT(RH.START_DATE, '%Y-%m-%d') as 'START_DATE',
    DATE_FORMAT(RH.END_DATE, '%Y-%m-%d') as 'END_DATE', 
    CASE
        WHEN (DATEDIFF(RH.END_DATE, RH.START_DATE) + 1 >= 30) THEN '장기 대여'
        ELSE '단기 대여'
    END AS 'RENT_TYPE'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
WHERE RH.START_DATE LIKE '2022-09%'
ORDER BY RH.HISTORY_ID DESC
