SELECT HISTORY_ID,
       CASE WHEN DISCOUNT_RATE IS NULL THEN ROUND(DAILY_FEE * DATE) 
       ELSE ROUND((DAILY_FEE - (DAILY_FEE*DISCOUNT_RATE/100)) * DATE) END AS FEE
FROM (SELECT DURATION_TYPE, DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE ='트럭') AS P
RIGHT OUTER JOIN (SELECT HISTORY_ID, DAILY_FEE,
                   DATEDIFF(END_DATE,START_DATE)+1 AS DATE,
                   (CASE 
                    WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 7 AND DATEDIFF(END_DATE,START_DATE)+1 < 30 THEN '7일 이상'
                    WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 30 AND DATEDIFF(END_DATE,START_DATE)+1 < 90 THEN '30일 이상'
                    WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 90 THEN '90일 이상'
                    ELSE NULL END) AS DURATION_TYPE 
                 FROM CAR_RENTAL_COMPANY_CAR AS A
                 JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B USING (CAR_ID)
                 WHERE A.CAR_TYPE ='트럭') AS C USING (DURATION_TYPE)
ORDER BY FEE DESC, HISTORY_ID DESC