SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS,
       ROUND(AVG(r.REVIEW_SCORE), 2) as SCORE
FROM REST_REVIEW r
JOIN REST_INFO i
ON i.REST_ID = r.REST_ID
GROUP BY r.REST_ID
HAVING i.ADDRESS like '서울%'
ORDER BY AVG(r.REVIEW_SCORE) DESC, i.FAVORITES DESC