SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W' 
      AND MONTH(DATE_OF_BIRTH) = 3 
      AND TLNO <> "NULL"
ORDER BY MEMBER_ID ASC